---
- hosts: localhost
  become: true
  gather_facts: yes
  tasks:
   - name: Import vars file
     include_vars: "vars/main.yml"
   - name: Setup
     import_tasks: "./stages/setup.yml"
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
     tags:
       - setup
   - name: System Configuration
     import_tasks: "./stages/system_configuration.yml"
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
     tags:
       - setup
   - name: GCP tools
     import_tasks: "./stages/gcp.yml"
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  #  - name: Vim
  #    import_tasks: "./stages/vim.yml"
    #  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
   - name: NeoVim
     import_tasks: "./stages/nvim.yml"
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
     tags:
       - nvim 
       - tunning
       - development
   - name: ZSH
     import_tasks: "./stages/zsh.yml"
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
     tags:
       - zsh 
       - tunning
   - name: Tunning
     import_tasks: "./stages/tools_tunning.yml"
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
     tags:
       - tunning
