---
 - name: Import vars file
   include_vars: "../../vars/main.yml"

 - name: Install Golang Dependencies
   apt:
     pkg: [ 'curl', 'gcc', 'git', 'findutils', 'make', 'rsync', 'tar' ]
     state: present
     update_cache: yes

 - name : Create needed paths for installation
   file:
     path: "{{ item }}"
     state: directory
     owner: "root"
     group: "root"
   with_items:
     - "{{ development.golang.install_dir }}/go{{ development.golang.version }}"
     - "{{ development.golang.download_dir }}{{ development.golang.version }}/"

 - name: "Download Golang {{ development.golang.version }}"
   get_url:
     url: "{{ development.golang.mirror }}{{ development.golang.version }}.linux-amd64.tar.gz"
     dest: "{{ development.golang.download_dir }}{{ development.golang.version }}/"

 - name: "Extract Golang {{ development.golang.version }}"
   ansible.builtin.unarchive:
     src: "{{ development.golang.download_dir }}{{ development.golang.version }}/go{{ development.golang.version  }}.linux-amd64.tar.gz"
     dest: "{{ development.golang.install_dir }}go{{ development.golang.version }}/"

 - name: Refresh Config
   sudo: no
   shell: "source /home/{{ global.user }}/.zshrc"
   args:
     executable: /bin/bash

