---
 - name: Add NeoVim repository
   ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
   loop:
    - "ppa:neovim-ppa/unstable"

 - name: Setup VIM
   apt:
     name: neovim
     state: present
     update_cache: yes

 - name: Download Plug Installer
   shell: |
     sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

 - name: Create paths needed for VIM
   file:
     path: "/home/{{ username }}/.config/{{ item }}/"
     state: directory
     owner: "{{ username }}"
     group: "{{ username }}"
   with_items:
     - nvim
     - nvim/plugin/
     - nvim/lua/

 - name: Copy file configuration
   ansible.builtin.copy:
     src: "../files/vim/{{ item }}"
     dest: "/home/{{ username }}/.config/nvim/{{ item }}"
     owner: "{{ username }}"
     group: "{{ username }}"
     mode: '0644'
   with_items:
     - init.vim

 - name: Copy Lua files
   ansible.builtin.copy:
     src: "../files/vim/{{ item }}"
     dest: "/home/{{ username }}/.config/nvim/{{ item }}/"
     owner: "{{ username }}"
     group: "{{ username }}"
     mode: '0644'
   with_items:
     - lua/

 - name: Copy Plugin folder
   ansible.builtin.copy:
     src: "../files/vim/{{ item }}"
     dest: "/home/{{ username }}/.config/nvim/{{ item }}/"
     owner: "{{ username }}"
     group: "{{ username }}"
     mode: '0644'
   with_items:
     - plugin/

 - name: Install plugins VIM
   command: vim +'PlugInstall --sync' +qa