---
# - name: Add NeoVim repository
#   ansible.builtin.apt_repository:
#    repo: "{{ item }}"
#    state: present
#   loop:
#    - "ppa:neovim-ppa/unstable"

 - name: Setup VIM
   apt:
     name: "{{ item }}"
     state: present
     update_cache: yes
   with_items:
     - python3-pip
     - neovim

 - name: Download Plug Installer
   shell: |
     sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

 - name: Create paths needed for VIM
   file:
     path: "/home/{{ username }}/.config/{{ item }}/"
     state: directory
     owner: "{{ username }}"
     group: "{{ username }}"
   with_items:
     - nvim

 - name: Copy all config files
   copy:
     src: ../files/nvim
     dest: "/home/{{ username }}/.config/"
     owner: "{{ username }}"
     group: "{{ username }}"
     mode: '0644'