---
 - name: Setup VIM
   apt:
     name: vim
     state: present
     update_cache: yes

 - name: Copy file configuration
   ansible.builtin.copy:
     src: ../files/vim/vimrc
     dest: "/home/{{ username }}/.vimrc"
     owner: "{{ username }}"
     group: "{{ username }}"
     mode: '0644'

 - name: Install plugins inline
   command: vim +PlugInstall +qall 
