---
 - name: Setup VIM
   apt:
     name: vim
     state: present
     update_cache: yes

 - name: Download VIM autoload
   get_url:
     url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
     dest: "/home/{{ username }}/.vim/autoload/plug.vim"
     owner: joseramon
     mode: '0440'

 - name: Copy file configuration
   ansible.builtin.copy:
     src: ../files/vim/vimrc
     dest: "/home/{{ username }}/.vimrc"
     owner: "{{ username }}"
     group: "{{ username }}"
     mode: '0644'