---
 - name: Setup VIM
   apt:
     name: "{{ item }}"
     state: present
     update_cache: yes
   loop:
    - git
    - vim
    - zsh

 - name: Copy file with owner and permissions
   ansible.builtin.template:
     src: ../templates/zshrc.j2
     dest: "/home/{{ username }}/.zshrc"
     owner: "{{ username }}"
     group: "{{ username }}"
     mode: '0644'

 - name: Load ZSH
   #become_user: "{{ username }}"
   shell: "chsh -s $(which zsh)"
   
 - name: Download ZSH
   get_url:
     url: "{{ item }}"
     dest: "/home/{{ username }}/.oh-my-zsh/custom/plugins/"
     force: no
   loop:
    - https://github.com/zsh-users/zsh-syntax-highlighting.git
